### ISSUE TITLE
[BUG] Request connector does not parse JSON correctly

### ISSUE THREAD

**Issue by mincequi** [thingsboard/thingsboard-gateway#1152]
The request connector does not parse this json correctly:
```
{
"temperature":33.46,
"overtemperature":false,
"tmp":{"tC":33.46,"tF":92.23, "is_valid":true},
"temperature_status":"Normal",
"ext_sensors":{"temperature_unit":"C"},
"ext_temperature":{
    "0":{
        "hwID":"284b0b4d182006ed","tC":47.62,"tF":117.73
    }
}
}
```

```
        "attributes": [
          {
            "key": "temp1",
            "type": "double",
            "value": "${tmp.tC}"
          },
          {
            "key": "temp2",
            "type": "double",
            "value": "${ext_temperature.0.tC}"
          }
        ]
```

I can actually parse tmp.tC, however ext_temperature.0.tC is not parsed.
Thanks in advance.

**Comment by samson0v** [comment]
Hi @mincequi, thanks for your interest in ThingsBoard IoT Gateway!
You can use the following expression: `"value": "${ext_temperature.*.tC}"`
<img width="283" alt="image" src="https://github.com/thingsboard/thingsboard-gateway/assets/43861229/10180c4d-b4d6-44fa-a74f-dd7d24a7c50c">
You can't use number as a key of dict because parser expect array instead of a dict.

**Comment by samson0v** [comment]
Hi @mincequi, can we close the issue?

**Comment by mincequi** [comment]
@samson0v yes, this can be closed.

Thanks a lot!
