### ISSUE TITLE
[BUG] Service RPC Reboot is not working.

### ISSUE THREAD

**Issue by samy4sam** [thingsboard/thingsboard-gateway#1237]
**Describe the bug**
When I send a reboot RPC to the gateway, the gateway does not restart. The command is not found by the gateway.
Other RPCs such as Ping or Restart work as intended.

**Error traceback (If available):**
![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/ae8dbb12-8cbb-48d8-a41b-4058d0022503)

![image](https://github.com/thingsboard/thingsboard-gateway/assets/42201209/6a3d783f-c600-47a4-9f8c-3c377ec44b34)

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04.6
 - Thingsboard IoT Gateway version: 3.4.3

**Comment by imbeacon** [comment]
Hi @samy4sam ,

Thank you for your interest in Thingsboard IoT Gateway.
You are right in some operation systems alias "reboot" may not be accessible by the gateway or they don't have it at all. I have updated the reboot command to use "shutdown -r now" instead of reboot. Please try to use the version from the master branch or wait for release.
