### ISSUE TITLE
[HELP]  RuntimeError: Message publish failed: The client is not currently connected.

### ISSUE THREAD

**Issue by DuXiaoChuang** [thingsboard/thingsboard-gateway#1368]
**Describe the issue**
RuntimeError: Message publish failed: The client is not currently connected.

![image](https://github.com/thingsboard/thingsboard-gateway/assets/149569575/ddbb9eaa-739b-4282-90e4-eaeb52cd2ed3)

**Versions (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Thingsboard IoT Gateway version [e.g. 3.0.1]
 - Python version[e.g. 3.9]

**Comment by imbeacon** [comment]
Hi @DuXiaoChuang,

Thank you for your interest in ThingsBoard IoT Gateway.
The connection to ThingsBoard was lost. It may be caused by a lot of reasons, beginning from network issues and ending with issues with a code.
We can suggest to try to use the latest version of the gateway code and check your network. Please feel free to open a new issue if the error persists and provide logs of the gateway on Debug level, because we cannot figure out what happened and how to reproduce the issue to solve it without detailed logs.
