### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard-gateway#144]
Hi!

I'm using tb gateway 1.2.2, it worked fine, when i restarted, it didn't want to work.
I have found this error message.

Java HotSpot(TM) 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGTERM to handler- the VM may need to be forcibly terminated

What should i do?

**Comment by mp-loki** [comment]
tb gateway 1.2.2 uses paho mqtt library to send messages to ThingsBoard. It is known to have issues on a high load, that's why it was replaced with netty-mqtt in tb gateway version 1.4. 
I suggest you upgrade to the latest version of tb-gateway (note that you will have to update your tb-gateway.yml file)
If you do not want to upgrade, I suggest you delete paho mqtt buffer file(s) and then restart the gateway (I can't recall the exact location of the paho files, but it's somewhere under /etc/tb-gateway/)
