### ISSUE TITLE
Disable data buffering in gateway

### ISSUE THREAD

**Issue by JozsefGuyas** [thingsboard/thingsboard-gateway#146]
Hi,
Can I disable the buffering in the tbgateway?

**Comment by mp-loki** [comment]
You can decrease the buffer size, but you cannot disable the buffer, because that approach has proven to cause data loss.

**Comment by JozsefGuyas** [comment]
what will happen if i wiil decrase the buffer size?

**Comment by mp-loki** [comment]
it will just decrease the number of messages stored in a single file, thus increasing the number of files. You may want to do this for performance reasons

**Comment by zbeacon** [comment]
Hi, @JozsefGuyas 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.
The new gateway supports "memory" storage and you can set it size.
You can read more [here](https://thingsboard.io/docs/iot-gateway/configuration/#storage-configuration).
