### ISSUE TITLE
How sends the client and shared attributes to device through the Thingsboard Gateway

### ISSUE THREAD

**Issue by amarras63** [thingsboard/thingsboard-gateway#150]
I'm trying to use the thingsboard gateway. I have no problems sending data from a device via the gateway to thingsboard using mqtt: the device is created and the telemetry data sent.
I can not read and send device attributes (client and shared attributes).
It's possible to do it?
I need a sample code where the device (eg Arduino or an ESP) is connected to the Thingsboard server via the Thingsboard Gateway (for example installed in a Raspberry) and receives and sends the client and shared attributes through the gateway (in addition to the telemetry that I can already send).

**Comment by mp-loki** [comment]
What gateway extension are you using?

**Comment by amarras63** [comment]
Hi Valerij,
I used the default configuration with the file
https://thingsboard.io/docs/iot-gateway/resources/mqtt-gui-extension-configuration.json


Il giorno sab 8 dic 2018, 22:51 Valerii Sosliuk <notifications@github.com>
ha scritto:

**Comment by zbeacon** [comment]
Hi, @amarras63 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.

We look forward to your feedback.
