### ISSUE TITLE
TB-Gateway Refuses to start due Java version being 1.8

### ISSUE THREAD

**Issue by GwenStouthuysen** [thingsboard/thingsboard-gateway#174]
I try to start TB-gateway as a service but it is refused.

The error as logged is a bit confusing and I really don't know how t handle it:
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion' has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

If I read this well I should use Java 1.7

But all my other software do require Java 1.8

Version is the actual 2.2.1, downloaded this morning.

**Comment by zbeacon** [comment]
Hi, @GwenStouthuysen 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
 - Less footprint and memory impact
 - Easier to extend and customize
 - Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.
