### ISSUE TITLE
OPC-UA write data

### ISSUE THREAD

**Issue by abrasat** [thingsboard/thingsboard-gateway#18]
Is the write access for OPC-UA data planned in the near future ?

**Comment by zbeacon** [comment]
Hi, @abrasat 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway. It supports write access data for OPC-UA. You can read more [here](https://thingsboard.io/docs/iot-gateway/config/opc-ua/).

We look forward to your feedback.
