### ISSUE TITLE
changed mapping didn't remove the old mapping

### ISSUE THREAD

**Issue by lincoln310** [thingsboard/thingsboard-gateway#211]
Hi i use a topic: sensors to report my telemetry data: position. I use loc1, loc2, loc3 to map to X Y Z. Then i changed the mapping to locx locy locz to X Y Z, but i also send old loc1 loc2 loc3 with different values against locx locy locz.  But it turned out that the two different values both appeared.

**Comment by zbeacon** [comment]
Hi, @lincoln310 

I am glad to inform you that we have released new version of the Gateway based on Python. This is a major rewrite and improvement from Java version. Main benefits:
Less footprint and memory impact
Easier to extend and customize
Improved functionality.

You can try using a new gateway for your purposes instead of a Java gateway.

We look forward to your feedback.
