### ISSUE TITLE
Compatibility with thingsboard 2.3.1

### ISSUE THREAD

**Issue by hasikp1** [thingsboard/thingsboard-gateway#321]
I have deployment of the thingsboard CE 2.3.1. Newest python gateway will it work with that? or is there a new version that is compatible?

**Comment by zbeacon** [comment]
Hi @hasikp1,

Thank you for your interest in the ThingsBoard IoT gateway. 

The gateway uses the ThingsBoard gateway API to communicate with it, but it is a different product and you don't have to use the same versions of the ThingsBoard and the gateway.
We recommend to us the latest version of the gateway, because usually it has more functionality and less bugs.
