### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by iminke** [thingsboard/thingsboard-gateway#341]
since installing the latest tb-gateway from docker my tb-gateway has stopped working.
""2020-07-09 01:14:03" - ERROR - [mqtt_connector.py] - mqtt_connector - 193 - [Errno 111] 
FAIL with error 5 not authorised"

I stopped both mosquttio and thingsboard and the error did not change so I wire sharked 127.0.0.1 and my local IP address and although I can see MQTT traffic from my devices, there is no traffic from thingsboard or tb-gateway.
It looks to me that the docker container for the tb-gateway is no communicating with the local host. This is also confirmed by the configuration, log and extension files being propagated to the localhost which they did in the past.
I would appreciate some help with this.

**Comment by zbeacon** [comment]
Hi @iminke 

Thank you for your interest in the ThingsBoard IoT gateway. Please try to use the IP address of your computer in the docker network instead of "localhost", usually it is something like "172.17.0.1".

To get the IP address of your computer in the docker network - please use the following command:
`docker inspect tb-gateway | grep \"Gateway\"`
