### ISSUE TITLE
[HELP] tb-gateway suddenly stop working. How to change QoS?

### ISSUE THREAD

**Issue by DanielRichart** [thingsboard/thingsboard-gateway#376]
**Describe the issue**
Hello,

I have thingsboard and the java version of tb-gateway running on an ubuntu machine. I am facing an issue that the gateway suddenly stops receiving messages from time to time. When it stops, the log file are full of 

[pool-3-thread-1] INFO o.t.g.service.MqttMessageSender - Waiting until all messages are sent before going to the next bucket
[pool-3-thread-1] INFO o.t.g.service.MqttMessageSender - Outgoing queue is not empty. [1] messages are still in progress

If i remove the mqtt extension config file from the gateway device, restart the gateway service and put the config file back on, it works again.

I did some research on the github issues, and apparently it could be a qos problem. In the other issues, modifications on the MqttMessageSender.java file are described (https://github.com/thingsboard/thingsboard-gateway/issues/106 and https://github.com/thingsboard/thingsboard-gateway/issues/121 )

I can't find this file on my system to try the modifications.

Please, where is this file? or there is another whay that i can set the mqtt qos to 0?

Thank you,
Daniel Richart

**Comment by zbeacon** [comment]
Hi @DanielRichart ,

Thank you for your message.
At first point - I have to say that the java version of the gateway is no longer supported, but to change the QoS there, you should clone the sources from the repository, change qos in file, you described, build the project and install your version of the gateway.

At second point - you are able to use the python version of the gateway, there you are able to set qos directly in the configuration tb_gateway.yaml in thingsboard section (parameter qos). It relates to all messages between ThingsBoard instance and the gateway.

Also, this behavior of the java-gateway can be caused by mqtt message size limit in ThingsBoard, you can try to increase max_payload_size parameter (mqtt - netty section) in thingsboard.yml on ThingsBoard instance to 2000000 for test, restart ThingsBoard and check the issue. It can be one of the possible causes of this behavior.
