### ISSUE TITLE
Unable to connect through opc ua also not generating errors.[HELP]

### ISSUE THREAD

**Issue by akashagre** [thingsboard/thingsboard-gateway#786]
![Screenshot (35)](https://user-images.githubusercontent.com/80543140/159903509-d323ff47-c106-4a7d-9a03-c94b125739ff.png)
![Screenshot (36)](https://user-images.githubusercontent.com/80543140/159903523-ee813ce1-e163-4f7c-a101-c204616d48e5.png)

**Comment by samson0v** [comment]
Hi @akashagre, it will be unable to see the logs because of the STREAM ONLY mode of your virtual machine.
Please, use the docker image if you are using Windows.

**Comment by Andhuooo** [comment]
Hi , can you  show the code of opcua server or  can you please connect it with thw prosys opcua client and share the  window screen shot .

**Comment by samson0v** [comment]
@akashagre, I can't help you because of your `STREAM ONLY` mode of your virtual machine, it is makes reading logs unavailable.

**Comment by samson0v** [comment]
@akashagre, a situation like this may appear because the gateway cannot write logs to the log file. The most common reasons are:
- logs folder doesn't exist (Using the version from the repository you should create the logs folder manually in the root of the repository folder, in another case please check if the path to the logs folder exists)
- thingsboard_gateway user doesn't have permission to write to the logs folder.

**Comment by samson0v** [comment]
Hi @akashagre, any updates? Can we close the issue?

**Comment by samson0v** [comment]
Hi @akashagre, any updates?
