### ISSUE TITLE
[HELP] How to determine thingsboard-gateway version & run update service behind a proxy 

### ISSUE THREAD

**Issue by cowherdboy** [thingsboard/thingsboard-gateway#852]
Hello,

I would like to know how to do the following:

1) Determine the thingsboard-gateway version that I am running

2) I am behind a proxy and the update service is unable to connect to the update server. Do I need to specify the proxy address and port somewhere as I do with the thingsboard license server? 

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - Thingsboard IoT Gateway version 3.1]
 - Python version 3.8

**Comment by samson0v** [comment]
Hi @cowherdboy, 
1. you can see the Gateway version at the top of logs as in the example below:
    <img width="1092" alt="зображення" src="https://user-images.githubusercontent.com/43861229/176117516-a4ed6d90-d567-49e9-8c11-39c5e4bbae50.png">
    or if you are using source code, you can see it in the `setup.py` file.
2. you can't specify the proxy for the update service (honestly, you do not need to do this, because apart from notifications there will be nothing more useful for you)

Thanks for your interest in ThingsBoard IoT Gateway!

**Comment by samson0v** [comment]
Hi @cowherdboy, can we close the issue?

**Comment by cowherdboy** [comment]
Hi @samson0v, Thank you for your helpful feedback. The issue may be closed.
